const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function harness(){
  const timers=new Map();let next=0;const context={window:{},Map,Date,Math,console,setTimeout:(fn,ms)=>{timers.set(++next,fn);return next;},clearTimeout:id=>timers.delete(id),WebSocket:function(){throw Error('Socket constructor forbidden');},fetch:()=>{throw Error('HTTP forbidden');}};
  context.window=context;vm.createContext(context);
  for(const file of ['core/game2048','core/sudoku-gen','core/2048','core/sudoku','core/minesweeper','core/gomoku','core/gomoku-ai','local/solo-runtime','local/solo-adapters','game-catalog'])vm.runInContext(fs.readFileSync('public/js/'+file+'.js','utf8'),context,{filename:file});
  const views=[],errors=[],statuses=[];let inits=0,destroys=0;
  return {context,timers,errors,views,statuses,create(id){return context.SoloRuntime.create({game:id,mount:{},renderer:{init:()=>inits++,render:view=>views.push(view),destroy:()=>destroys++},onError:e=>errors.push(e),onStatus:s=>statuses.push(s),strings:{thinking:'thinking',paused:'paused'}});},inits:()=>inits,destroys:()=>destroys,ai(){const [id,fn]=timers.entries().next().value;timers.delete(id);fn();}};
}
test('solo metadata lists exactly the four supported games and matches registered adapters',()=>{const h=harness(),games=Array.from(h.context.gameCatalog.list().filter(g=>g.solo));assert.deepEqual(games.map(g=>g.id).sort(),['2048','gomoku','minesweeper','sudoku']);for(const g of games)assert.ok(h.context.SoloRuntime.has(g.id));assert.equal(h.context.gameCatalog.byId('gomoku').solo,'local-ai');});
test('local 2048 merges, spawns and restarts without a room or transport',()=>{const h=harness(),runtime=h.create('2048'),state=runtime.getState();assert.equal(state.boards.length,1);state.boards[0]=[[2,2,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]];assert.equal(runtime.makeMove({dir:'left'}),true);assert.equal(state.boards[0][0][0],4);assert.equal(state.scores[0],4);assert.equal(h.views.at(-1).board,state.boards[0]);runtime.restart();assert.notEqual(runtime.getState(),state);assert.equal(runtime.getState().scores[0],0);assert.equal(h.inits(),2);});
test('local Sudoku generates, accepts input, hints and detects completion',()=>{const h=harness(),runtime=h.create('sudoku'),state=runtime.getState();assert.equal(state.puzzle.length,9);const blanks=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(!state.given[r][c])blanks.push([r,c]);const [r,c]=blanks[0];assert.equal(runtime.makeMove({row:r,col:c,val:state.solution[r][c]}),true);assert.equal(state.counts[0],1);assert.equal(runtime.makeMove({type:'hint'}),true);assert.equal(state.hints[0],2);for(const [row,col]of blanks)if(!state.filled[0][row][col])runtime.makeMove({row,col,val:state.solution[row][col]});assert.equal(state.winner,0);assert.equal(Object.hasOwn(h.views.at(-1),'solution'),false);runtime.restart();assert.equal(runtime.getState().winner,null);});
test('local minesweeper supports flags, reveal, win, loss and restart',()=>{const h=harness(),runtime=h.create('minesweeper'),state=runtime.getState();assert.equal(state.mines.length,10);let safe,mine;for(let row=0;row<10;row++)for(let col=0;col<10;col++){if(state.mines[row][col])mine={row,col};else safe={row,col};}runtime.makeMove({action:'flag',...mine});assert.equal(state.flagged[0][mine.row][mine.col],true);runtime.makeMove({action:'flag',...mine});runtime.makeMove({action:'reveal',...safe});assert.ok(state.cellsRevealed[0]>0);runtime.makeMove({action:'reveal',...mine});assert.equal(state.winner,-1);runtime.restart();const next=runtime.getState();for(let row=0;row<10;row++)for(let col=0;col<10;col++)if(!next.mines[row][col])runtime.makeMove({action:'reveal',row,col});assert.equal(next.winner,0);});
test('Gomoku human move schedules browser-local AI, blocks extra clicks and alternates turns',()=>{const h=harness(),runtime=h.create('gomoku'),state=runtime.getState();runtime.makeMove({row:7,col:7});assert.equal(state.currentPlayer,1);assert.equal(h.statuses.at(-1),'thinking');assert.equal(h.timers.size,1);assert.equal(runtime.makeMove({row:7,col:8}),false);h.ai();assert.equal(state.currentPlayer,0);assert.equal(state.board.flat().filter(x=>x===1).length,1);assert.equal(state.board[7][7],0);});
test('Gomoku AI takes a winning move; shared rules detect human wins',()=>{const h=harness(),runtime=h.create('gomoku'),state=runtime.getState();for(let c=3;c<7;c++)state.board[5][c]=1;const snapshot=JSON.stringify(state.board);const move=h.context.GomokuAI.getMove(state,1);assert.equal(JSON.stringify(state.board),snapshot);assert.equal(h.context.LocalGameCores.gomoku.handleMove(move,{...state,currentPlayer:1},1),null);assert.ok(state.board[5][2]===1||state.board[5][7]===1);
  runtime.restart();const next=runtime.getState();for(let c=3;c<7;c++)next.board[7][c]=0;runtime.makeMove({row:7,col:7});assert.equal(next.winner,0);assert.equal(h.timers.size,0);});
test('pause/resume/restart/destroy cancel stale local AI work and prevent later moves',()=>{const h=harness(),runtime=h.create('gomoku');runtime.makeMove({row:7,col:7});runtime.pause();assert.equal(h.timers.size,0);assert.equal(runtime.makeMove({row:1,col:1}),false);runtime.resume();assert.equal(h.timers.size,1);runtime.restart();assert.equal(h.timers.size,0);runtime.makeMove({row:7,col:7});runtime.destroy();runtime.destroy();assert.equal(h.timers.size,0);assert.equal(h.destroys(),1);assert.equal(runtime.makeMove({row:1,col:1}),false);});
test('solo room-client dispatch runs before all multiplayer storage, DOM and socket access',()=>{const credentials={roomId:'ABC',resumeToken:'secret',playerIndex:'2',game:'uno'},before=JSON.stringify(credentials);let starts=0;const context={window:{__SOLO_MODE:true,startSoloGame:()=>starts++},sessionStorage:{getItem(){throw Error('Multiplayer storage read');},setItem(){throw Error('Multiplayer storage write');}},document:{getElementById(){throw Error('Room DOM access');}},WebSocket(){throw Error('Socket constructor');}};vm.runInNewContext(fs.readFileSync('public/js/room-client.js','utf8'),context);assert.equal(starts,1);assert.equal(JSON.stringify(credentials),before);});
test('solo reuses the four existing renderer files and browser assets have no Node dependencies',()=>{const html=fs.readFileSync('public/game.html','utf8');for(const id of ['2048','sudoku','minesweeper','gomoku'])assert.equal((html.match(new RegExp('/js/renderers/'+id+'\\.js','g'))||[]).length,1);for(const dir of ['local','core'])for(const file of fs.readdirSync('public/js/'+dir)){const source=fs.readFileSync('public/js/'+dir+'/'+file,'utf8');assert.equal(/\brequire\s*\(|\bprocess\.|\bWebSocket\b|\bfetch\s*\(/.test(source),false,file);}});
